### ISSUE TITLE
Publish `0.1.0`

### ISSUE THREAD

**Issue by SNDST00M** [SNDST00M/starfall-visual-studio-code#1]
## `0.1.0`

- [x] Cross-channel testing for `0.1.0` (VSC stable, insiders, VSCodium).
- [x] Update asset references.
- [ ] Create tag release for GitHub.
- [ ] Publish `0.1.0` to Extension Marketplace.
- [ ] Publish `0.1.0` to OpenVSX.

## Changelog

Initial version:
 
- Four variants: Default, Darker, Ocean, Palenight.
- Supports these modes:
  - Programming languages: C/C++, CSS/Less/SCSS, Elixir, Go, INI, Markup languages, PHP, TypeScript, Java, JavaScript.
  - Static formats: Diff, HTML, Markdown, markup, JSON, reStructured Text, XML, YAML.
- Screenshots for editor overview, installation and color scheme.
- Test workflow includes color theme validation and linting.
