### ISSUE TITLE
Publish `0.1.1`

### ISSUE THREAD

**Issue by SNDST00M** [SNDST00M/starfall-visual-studio-code#5]
## `0.1.1`

- [x] Cross-channel testing for `0.1.1` (VSC stable, insiders, VSCodium).
- [x] Update asset references.
- [x] Create tag release for GitHub.
- [x] Publish `0.1.1` to Extension Marketplace.
- [x] Publish `0.1.1` to OpenVSX.

## Changelog

- Fix publisher field in package data.
- Fix build badge in documentation.
